# Generated by Django 6.0.7 on 2026-07-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=10, unique=True, verbose_name='SKU/Cod')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('Laptops', 'Laptops'), ('Escritorio', 'Escritorio'), ('Perifericos', 'Perifericos'), ('Impresion', 'Impresion'), ('Almacenamiento', 'Almacenamiento'), ('Audio y Video', 'Audio y Video'), ('Mobiliario', 'Mobiliario')], max_length=30)),
                ('costo_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
    ]
