# Generated by Django 6.0.7 on 2026-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movimientostock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], max_length=10)),
                ('fecha', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
                ('cliente_proveedor', models.CharField(max_length=120, verbose_name='Cliente / Proveedor')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio_pago', models.CharField(choices=[('Banco BHD', 'Banco BHD'), ('Caja Chica', 'Caja Chica'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], max_length=20)),
                ('factura', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
