# Generated by Django 6.0.7 on 2026-08-07 02:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movimientofinanciero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='cliente_proveedor',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cliente / Proveedor'),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('Banco BHD', 'Banco BHD'), ('Caja Chica', 'Caja Chica'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], max_length=20),
        ),
    ]
