# Generated by Django 6.0.7 on 2026-08-13 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_movimientofinanciero_cliente_proveedor_and_more'),
        ('core', '0004_cliente_venta_detalleventa'),
    ]

    operations = [
    ]
