# Generated by Django 6.0.7 on 2026-08-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260812_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('puesto', models.CharField(max_length=100)),
                ('departamento', models.CharField(choices=[('Ventas', 'Ventas'), ('Finanzas', 'Finanzas'), ('Inventario', 'Inventario'), ('Admin', 'Admin')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'ordering': ['-venta__fecha']},
        ),
    ]
