# Generated by Django 6.0.7 on 2026-08-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_empleado_alter_detalleventa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Financiero', 'Financiero'), ('Ventas', 'Ventas'), ('Inventario', 'Inventario')], max_length=20)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('formato', models.CharField(choices=[('PDF', 'PDF'), ('Excel', 'Excel')], default='PDF', max_length=10)),
                ('archivo', models.FileField(upload_to='reportes/')),
            ],
            options={
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
