# Generated by Django 6.0.7 on 2026-08-17 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reportegenerado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de acceso'),
        ),
        migrations.CreateModel(
            name='PermisoPagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('Ventas', 'Ventas'), ('Finanzas', 'Finanzas'), ('Inventario', 'Inventario'), ('Admin', 'Admin')], max_length=20)),
                ('pagina', models.CharField(choices=[('dashboard', 'Dashboard'), ('productos', 'Productos'), ('ventas', 'Ventas'), ('finanzas', 'Finanzas'), ('inventario', 'Inventario'), ('proyecciones', 'Proyecciones'), ('clientes', 'Clientes'), ('empleados', 'Empleados'), ('reportes', 'Reportes')], max_length=30)),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_crear', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['departamento', 'pagina'],
                'unique_together': {('departamento', 'pagina')},
            },
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_username', models.CharField(max_length=150)),
                ('accion', models.CharField(choices=[('Eliminar Cuenta', 'Eliminar Cuenta'), ('Reiniciar Ventas del Mes', 'Reiniciar Ventas del Mes')], max_length=50)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empleado')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
