# Generated by Django 6.0.7 on 2026-08-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_empleado_usuario_permisopagina_registroactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(default='Cromf Finanzas', max_length=150)),
                ('rnc', models.CharField(blank=True, max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('moneda', models.CharField(choices=[('RD$ - Peso Dominicano', 'RD$ - Peso Dominicano'), ('US$ - Dolar', 'US$ - Dolar')], default='RD$ - Peso Dominicano', max_length=30)),
                ('itbs_porcentaje', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Datos de la Empresa',
                'verbose_name_plural': 'Datos de la Empresa',
            },
        ),
    ]
