# Generated by Django 6.1 on 2026-08-22 02:33
"""
Migración de datos: asigna a los 5 roles (Group) ya existentes en el
proyecto los permisos dinámicos equivalentes a lo que ya tenían hoy en
core/permisos.py (MODULOS y ESCRITURA).

No crea ni elimina roles, no toca auth_user_groups. Su único objetivo
es que, cuando en una fase posterior el backend pase a validar con
user.has_perm(...), ningún usuario existente pierda el acceso que
tiene actualmente. Es idempotente y reversible.
"""
from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations

# Mismo mapeo que MODULOS/ESCRITURA en core/permisos.py, expresado en
# términos de los nuevos codenames de permiso.
PERMISOS_POR_ROL = {
    'Administrador': [
        'ver_dashboard', 'ver_ventas', 'ver_productos', 'crear_productos',
        'ver_finanzas', 'ver_inventario', 'ver_proyecciones', 'ver_clientes',
        'ver_empleados', 'ver_reportes', 'ver_configuracion', 'ver_usuarios',
        'gestionar_roles',
    ],
    'Gerente': [
        'ver_dashboard', 'ver_ventas', 'ver_productos', 'crear_productos',
        'ver_finanzas', 'ver_inventario', 'ver_proyecciones', 'ver_clientes',
        'ver_empleados', 'ver_reportes',
    ],
    'Finanzas': [
        'ver_dashboard', 'ver_finanzas', 'ver_proyecciones', 'ver_reportes',
    ],
    'Inventario': [
        'ver_dashboard', 'ver_productos', 'crear_productos', 'ver_inventario',
        'ver_reportes',
    ],
    'Cajero': [
        'ver_dashboard', 'ver_ventas', 'ver_productos', 'crear_productos',
        'ver_clientes', 'ver_reportes',
    ],
}


def asignar_permisos(apps, schema_editor):
    # Los permisos personalizados de Meta.permissions normalmente los crea
    # la señal post_migrate, que se dispara DESPUÉS de terminar todo el
    # comando migrate. Como esta migración de datos corre en el mismo
    # comando que crea el modelo ModuloSistema, forzamos su creación aquí
    # para poder asignarlos ya mismo, de forma segura e idempotente.
    config_core = global_apps.get_app_config('core')
    create_permissions(config_core, verbosity=0)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for nombre_rol, codenames in PERMISOS_POR_ROL.items():
        grupo = Group.objects.filter(name=nombre_rol).first()
        if grupo is None:
            # El rol no existe en esta base de datos (proyecto nuevo,
            # por ejemplo); no hay nada que preservar para él.
            continue
        permisos = Permission.objects.filter(
            content_type__app_label='core',
            codename__in=codenames,
        )
        grupo.permissions.add(*permisos)


def revertir_permisos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for nombre_rol, codenames in PERMISOS_POR_ROL.items():
        grupo = Group.objects.filter(name=nombre_rol).first()
        if grupo is None:
            continue
        permisos = Permission.objects.filter(
            content_type__app_label='core',
            codename__in=codenames,
        )
        grupo.permissions.remove(*permisos)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_modulo_sistema_permisos'),
    ]

    operations = [
        migrations.RunPython(asignar_permisos, revertir_permisos),
    ]
