# Generated by Django 6.1 on 2026-08-22 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_permisos_roles_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulosistema',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_dashboard', 'Puede ver Dashboard'), ('ver_ventas', 'Puede ver Ventas'), ('ver_productos', 'Puede ver Productos'), ('crear_productos', 'Puede crear/editar Productos'), ('ver_finanzas', 'Puede ver Finanzas'), ('ver_inventario', 'Puede ver Inventario'), ('ver_proyecciones', 'Puede ver Proyecciones'), ('ver_clientes', 'Puede ver Clientes'), ('ver_empleados', 'Puede ver Empleados'), ('ver_reportes', 'Puede ver Reportes'), ('ver_configuracion', 'Puede ver Configuración'), ('ver_usuarios', 'Puede ver y gestionar Usuarios'), ('gestionar_roles', 'Puede crear, editar y eliminar Roles y Permisos'), ('gestionar_recuperaciones', 'Puede gestionar solicitudes de recuperación de contraseña')]},
        ),
        migrations.CreateModel(
            name='SolicitudRecuperacionPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada')], default='Pendiente', max_length=12)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('token_expira', models.DateTimeField(blank=True, null=True)),
                ('administrador_resolutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recuperacion_resueltas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de recuperación de contraseña',
                'verbose_name_plural': 'Solicitudes de recuperación de contraseña',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
