# Generated by Django 6.1
"""
Migracion de datos (Fase 4): otorga el permiso 'gestionar_recuperaciones'
unicamente al rol Administrador, igual que el patron de la Fase 1.

NO se toca ningun otro permiso de Administrador ni de los demas roles
(Gerente, Finanzas, Inventario, Cajero) - por eso este archivo solo
AGREGA un permiso a un unico grupo, nunca usa set() ni remove() sobre
el resto de la relacion.
"""
from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations

NOMBRE_ROL = 'Administrador'
CODENAME = 'gestionar_recuperaciones'


def otorgar_permiso(apps, schema_editor):
    # Igual que en 0012: forzamos la creacion de los permisos de
    # Meta.permissions aqui mismo, porque la señal post_migrate que
    # normalmente los crea se dispara DESPUES de terminar todo el
    # comando migrate, no entre esta migracion y la anterior.
    config_core = global_apps.get_app_config('core')
    create_permissions(config_core, verbosity=0)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    grupo = Group.objects.filter(name=NOMBRE_ROL).first()
    if grupo is None:
        return

    permiso = Permission.objects.filter(
        content_type__app_label='core', codename=CODENAME,
    ).first()
    if permiso is None:
        return

    grupo.permissions.add(permiso)


def revertir_permiso(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    grupo = Group.objects.filter(name=NOMBRE_ROL).first()
    if grupo is None:
        return

    permiso = Permission.objects.filter(
        content_type__app_label='core', codename=CODENAME,
    ).first()
    if permiso is None:
        return

    grupo.permissions.remove(permiso)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_recuperacion_password'),
    ]

    operations = [
        migrations.RunPython(otorgar_permiso, revertir_permiso),
    ]
