# Generated by Django 6.1 on 2026-08-23 00:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_seed_permiso_gestionar_recuperaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre / Razón social')),
                ('rnc', models.CharField(blank=True, max_length=20, verbose_name='RNC / Identificación')),
                ('contacto', models.CharField(blank=True, max_length=120, verbose_name='Persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='modulosistema',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_dashboard', 'Puede ver Dashboard'), ('ver_ventas', 'Puede ver Ventas'), ('ver_productos', 'Puede ver Productos'), ('crear_productos', 'Puede crear/editar Productos'), ('ver_finanzas', 'Puede ver Finanzas'), ('ver_inventario', 'Puede ver Inventario'), ('ver_proyecciones', 'Puede ver Proyecciones'), ('ver_clientes', 'Puede ver Clientes'), ('ver_empleados', 'Puede ver Empleados'), ('ver_reportes', 'Puede ver Reportes'), ('ver_configuracion', 'Puede ver Configuración'), ('ver_usuarios', 'Puede ver y gestionar Usuarios'), ('gestionar_roles', 'Puede crear, editar y eliminar Roles y Permisos'), ('gestionar_recuperaciones', 'Puede gestionar solicitudes de recuperación de contraseña'), ('ver_compras', 'Puede ver el módulo Compras'), ('gestionar_proveedores', 'Puede crear y editar Proveedores'), ('gestionar_ordenes_compra', 'Puede crear y gestionar Órdenes de compra'), ('gestionar_recepciones', 'Puede registrar Recepciones'), ('gestionar_compras', 'Puede registrar Compras y sus pagos')]},
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_articulo',
            field=models.CharField(choices=[('Mercancia', 'Mercancía (para la venta)'), ('Material', 'Material o insumo interno')], default='Mercancia', max_length=15),
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Enviada', 'Enviada'), ('Parcialmente recibida', 'Parcialmente recibida'), ('Recibida', 'Recibida / completada'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=25)),
                ('notas', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='core.proveedor')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden_compra', to='core.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.ordencompra')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='core.ordencompra')),
                ('recibido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.PositiveIntegerField()),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recepciones', to='core.detalleordencompra')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.recepcion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=30, verbose_name='Factura del proveedor')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condicion_pago', models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Crédito')], default='Contado', max_length=10)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente de pago'), ('Parcial', 'Parcialmente pagada'), ('Pagada', 'Pagada')], default='Pendiente', max_length=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_registradas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='core.ordencompra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='core.proveedor')),
                ('recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='core.recepcion')),
            ],
            options={
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
