# Generated by Django 6.1
"""
Migracion de datos (Fase 5): otorga los 5 permisos nuevos de Compras
(ver_compras, gestionar_proveedores, gestionar_ordenes_compra,
gestionar_recepciones, gestionar_compras) unicamente al rol
Administrador, siguiendo el mismo patron de la Fase 1 y la Fase 4.

NO se toca ningun otro permiso de Administrador ni de los demas roles
(Gerente, Finanzas, Inventario, Cajero): solo se AGREGAN permisos a un
unico grupo.
"""
from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations

NOMBRE_ROL = 'Administrador'
CODENAMES = [
    'ver_compras',
    'gestionar_proveedores',
    'gestionar_ordenes_compra',
    'gestionar_recepciones',
    'gestionar_compras',
]


def otorgar_permisos(apps, schema_editor):
    # Igual que en 0012/0014: forzamos la creacion de los permisos de
    # Meta.permissions aqui mismo, porque la señal post_migrate que
    # normalmente los crea se dispara DESPUES de terminar todo el
    # comando migrate, no entre esta migracion y la anterior.
    config_core = global_apps.get_app_config('core')
    create_permissions(config_core, verbosity=0)

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    grupo = Group.objects.filter(name=NOMBRE_ROL).first()
    if grupo is None:
        return

    permisos = Permission.objects.filter(
        content_type__app_label='core', codename__in=CODENAMES,
    )
    grupo.permissions.add(*permisos)


def revertir_permisos(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    grupo = Group.objects.filter(name=NOMBRE_ROL).first()
    if grupo is None:
        return

    permisos = Permission.objects.filter(
        content_type__app_label='core', codename__in=CODENAMES,
    )
    grupo.permissions.remove(*permisos)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_compras_modulo'),
    ]

    operations = [
        migrations.RunPython(otorgar_permisos, revertir_permisos),
    ]
