# Generated by Django 6.1 on 2026-08-24 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_permisos_compras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulosistema',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_dashboard', 'Puede ver Dashboard'), ('ver_ventas', 'Puede ver Ventas'), ('ver_productos', 'Puede ver Productos'), ('crear_productos', 'Puede crear/editar Productos'), ('ver_finanzas', 'Puede ver Finanzas'), ('ver_inventario', 'Puede ver Inventario'), ('ver_proyecciones', 'Puede ver Proyecciones'), ('ver_clientes', 'Puede ver Clientes'), ('ver_empleados', 'Puede ver Empleados'), ('ver_reportes', 'Puede ver Reportes'), ('ver_configuracion', 'Puede ver Configuración'), ('ver_usuarios', 'Puede ver y gestionar Usuarios'), ('gestionar_roles', 'Puede crear, editar y eliminar Roles y Permisos'), ('gestionar_recuperaciones', 'Puede gestionar solicitudes de recuperación de contraseña'), ('ver_compras', 'Puede ver el módulo Compras'), ('gestionar_proveedores', 'Puede crear y editar Proveedores'), ('gestionar_ordenes_compra', 'Puede crear y gestionar Órdenes de compra'), ('gestionar_recepciones', 'Puede registrar Recepciones'), ('gestionar_compras', 'Puede registrar Compras y sus pagos'), ('ver_pedidos_clientes', 'Puede ver Pedidos de Clientes'), ('gestionar_pedidos_clientes', 'Puede crear y gestionar Pedidos de Clientes')]},
        ),
        migrations.CreateModel(
            name='PedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega solicitada')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de cliente',
                'verbose_name_plural': 'Pedidos de clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido_cliente', to='core.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.pedidocliente')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
