# Generated by Django 6.1 on 2026-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_bootstrap_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PermisoPagina',
        ),
        migrations.AlterField(
            model_name='registroactividad',
            name='accion',
            field=models.CharField(choices=[('Eliminar Cuenta', 'Eliminar Cuenta')], max_length=50),
        ),
    ]
