# Generated by Django 6.1 on 2026-08-26 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_eliminar_permisopagina_y_choice_reset_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='detalle_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.detallepedidocliente'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='core.compra'),
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_financieros', to='core.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='core.pedidocliente'),
        ),
    ]
