# Generated by Django 6.1 on 2026-09-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_conectar_pedido_venta_y_trazabilidad_finanzas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocliente',
            name='fecha_vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia de la cotización (hasta)'),
        ),
        migrations.AlterField(
            model_name='pedidocliente',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Completado', 'Completado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=10),
        ),
    ]
