# Generated by Django 6.1 on 2026-09-01 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_pedidocliente_rechazado_vigencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def backfill_codigos_y_facturas(apps, schema_editor):
        """Asigna codigo/numero_factura a los registros que ya existían
        antes de este campo, ANTES de que el siguiente paso active la
        restricción unique=True. Sin esto, todos los registros
        existentes quedarían con el mismo valor por defecto ('') y la
        restricción unique fallaría al aplicarse (o, peor, se aplicaría
        sobre una base con duplicados)."""
        Cliente = apps.get_model('core', 'Cliente')
        for cliente in Cliente.objects.filter(codigo=''):
            cliente.codigo = f'CLI-{cliente.pk:06d}'
            cliente.save(update_fields=['codigo'])

        Venta = apps.get_model('core', 'Venta')
        for venta in Venta.objects.filter(numero_factura=''):
            venta.numero_factura = f'FAC-{venta.pk:06d}'
            venta.save(update_fields=['numero_factura'])

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rnc_cedula',
            field=models.CharField(blank=True, max_length=20, verbose_name='RNC/Cédula'),
        ),
        migrations.AddField(
            model_name='datosempresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_rnc_cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='condicion_pago',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Credito', 'Credito')], default='Contado', max_length=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_vendidas', to=settings.AUTH_USER_MODEL),
        ),
        # Backfill ANTES de exigir unicidad (ver función arriba).
        migrations.RunPython(backfill_codigos_y_facturas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
