# Generated by Django 6.1 on 2026-09-03 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_clientes_ventas_factura_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulosistema',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_dashboard', 'Puede ver Dashboard'), ('ver_ventas', 'Puede ver Ventas'), ('ver_productos', 'Puede ver Productos'), ('crear_productos', 'Puede crear/editar Productos'), ('ver_finanzas', 'Puede ver Finanzas'), ('ver_inventario', 'Puede ver Inventario'), ('ver_proyecciones', 'Puede ver Proyecciones'), ('ver_clientes', 'Puede ver Clientes'), ('ver_empleados', 'Puede ver Empleados'), ('ver_reportes', 'Puede ver Reportes'), ('ver_configuracion', 'Puede ver Configuración'), ('ver_usuarios', 'Puede ver y gestionar Usuarios'), ('gestionar_roles', 'Puede crear, editar y eliminar Roles y Permisos'), ('gestionar_recuperaciones', 'Puede gestionar solicitudes de recuperación de contraseña'), ('ver_compras', 'Puede ver el módulo Compras'), ('gestionar_proveedores', 'Puede crear y editar Proveedores'), ('gestionar_ordenes_compra', 'Puede crear y gestionar Órdenes de compra'), ('gestionar_recepciones', 'Puede registrar Recepciones'), ('gestionar_compras', 'Puede registrar Compras y sus pagos'), ('ver_pedidos_clientes', 'Puede ver Pedidos de Clientes'), ('gestionar_pedidos_clientes', 'Puede crear y gestionar Pedidos de Clientes'), ('ver_cuentas_por_cobrar', 'Puede ver Cuentas por Cobrar'), ('registrar_cobros', 'Puede registrar cobros de Cuentas por Cobrar')]},
        ),
        migrations.AddField(
            model_name='datosempresa',
            name='dias_credito',
            field=models.PositiveIntegerField(default=30, verbose_name='Plazo de crédito (días)'),
        ),
        migrations.CreateModel(
            name='Cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Banco BHD', 'Banco BHD'), ('Caja Chica', 'Caja Chica'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=60)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobros_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobro',
                'verbose_name_plural': 'Cobros',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='cobro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_financiero', to='core.cobro'),
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='core.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_por_cobrar_creadas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_cobrar', to='core.venta')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddField(
            model_name='cobro',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros', to='core.cuentaporcobrar'),
        ),
    ]
