# Generated by Django 6.1

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_seed_permisos_cuentas_por_cobrar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulosistema',
            options={'default_permissions': (), 'managed': False, 'permissions': [('ver_dashboard', 'Puede ver Dashboard'), ('ver_ventas', 'Puede ver Ventas'), ('ver_productos', 'Puede ver Productos'), ('crear_productos', 'Puede crear/editar Productos'), ('ver_finanzas', 'Puede ver Finanzas'), ('ver_inventario', 'Puede ver Inventario'), ('ver_proyecciones', 'Puede ver Proyecciones'), ('ver_clientes', 'Puede ver Clientes'), ('ver_empleados', 'Puede ver Empleados'), ('ver_reportes', 'Puede ver Reportes'), ('ver_configuracion', 'Puede ver Configuración'), ('ver_usuarios', 'Puede ver y gestionar Usuarios'), ('gestionar_roles', 'Puede crear, editar y eliminar Roles y Permisos'), ('gestionar_recuperaciones', 'Puede gestionar solicitudes de recuperación de contraseña'), ('ver_compras', 'Puede ver el módulo Compras'), ('gestionar_proveedores', 'Puede crear y editar Proveedores'), ('gestionar_ordenes_compra', 'Puede crear y gestionar Órdenes de compra'), ('gestionar_recepciones', 'Puede registrar Recepciones'), ('gestionar_compras', 'Puede registrar Compras'), ('ver_pedidos_clientes', 'Puede ver Pedidos de Clientes'), ('gestionar_pedidos_clientes', 'Puede crear y gestionar Pedidos de Clientes'), ('ver_cuentas_por_cobrar', 'Puede ver Cuentas por Cobrar'), ('registrar_cobros', 'Puede registrar cobros de Cuentas por Cobrar'), ('registrar_pagos_compra', 'Puede registrar pagos de Cuentas por Pagar')]},
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(blank=True, choices=[('Banco BHD', 'Banco BHD'), ('Caja Chica', 'Caja Chica'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=60)),
                ('observacion', models.CharField(blank=True, max_length=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='core.compra')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_compra_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago a proveedor',
                'verbose_name_plural': 'Pagos a proveedores',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='pago_compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_financiero', to='core.pagocompra'),
        ),
    ]
